version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  reviewers:
  - MarkusH
  allow:
  - dependency-type: direct
  - dependency-type: indirect
