version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - MarkusH
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: httpcore
    versions:
    - 0.13.0
  - dependency-name: jinja2
    versions:
    - 2.11.3
